name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 14, 16]

    name: ${{ matrix.os }} - Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: yarn install

      - run: yarn test

      - name: Coverage => (${{ matrix.os }} - Node ${{ matrix.node }})
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 12 }}
        run: yarn test --coverage

      - name: Dependencies Security Audit
        run: npx audit-ci --skip-dev --critical --package-manager yarn

  size:
    runs-on: ubuntu-latest

    name: size check (<= 500 KB)

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Dependencies
        run: yarn install

      - run: yarn size
